### ISSUE TITLE
Allow overriding the location of the build cache

### ISSUE THREAD

**Issue by pablochacin** [szkiba/k6x#18]
### Enhancement Description

Add a flag such as `--cache` to allow overriding the location of the build cache.

**Comment by szkiba** [comment]
Hi @pablochacin ,  I would like to ask you for clarification. What do you mean by **build cache**? What is the use case that this flag solves?

The binary location of k6 can be specified using the `--bin-dir` flag. In general, the location of the cache (used by k6x and e.g. go builder) can be specified in the `XDG_CACHE_HOME` environment variable. The go build cache can be specified in the `GOCACHE` environment variable. The go module cache can be specified in the `GOMODCACHE` environment variable.

Since k6x is primarily a k6 launcher, I try to minimize the number of flags to avoid potential conflicts with k6 flags.

It is conceivable that the k6x cache directory (which is currently k6x under `XDG_CACHE_HOME`) could be specified in a `K6X_CACHE_DIR` environment variable (and with a `--cache-dir` flag). Is this what you mean by **build cache**? This directory contains the k6x bin directory and the http cache used for build preparation. The http cache contains GitHub API responses to avoid restrictions caused by the rate limit. This is a small cache.

**Comment by pablochacin** [comment]
> It is conceivable that the k6x cache directory (which is currently k6x under XDG_CACHE_HOME) could be specified in a K6X_CACHE_DIR environment variable (and with a --cache-dir flag). Is this what you mean by build cache?

Yes. This is precisely what this issue is about.

> Since k6x is primarily a k6 launcher, I try to minimize the number of flags to avoid potential conflicts with k6 flags.

This is a valid point. A simple way to overcome this is to use `k6x` as a prefix for options. For example `k6x-build-cache`

**Comment by szkiba** [comment]
The next release will include `--cache-dir` and `K6X_CACHE_DIR` support.

I also thought about prefixing the flag, but it doesn't seem like an aesthetic solution. I have put the topic on hold for now until it causes a problem.

**Comment by pablochacin** [comment]
Awesome, thanks.

**Comment by szkiba** [comment]
Hi @pablochacin , The [v0.4.0](https://github.com/szkiba/k6x/releases/tag/v0.4.0) release includes this feature.
